### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by remcoder** [remcoder/OctoPrint-GCodeThumbs#4]
* Prevent layout from 'jumping'
 * maybe delay loading and rendering a bit

**Comment by jneilliii** [comment]
Great plugin.  What about using a button in the filelist and loading the preview with a modal pop-up?  I'm doing something like this in my plugin as noted [here](https://github.com/jneilliii/OctoPrint-UltimakerFormatPackage/blob/e79f136bd7368dcbd116fad2a3a9d6ab7a04611a/octoprint_ultimakerformatpackage/static/js/UltimakerFormatPackage.js#L26).

**Comment by remcoder** [comment]
Thanks for the suggestion. I'll look into it.

**Comment by jneilliii** [comment]
I haven't been able to get the canvas to update, but I have been able to get the framework for a pop-up thumbnail viewer done.  You can see what I did at the link below.  It seems to work the first time you open but doesn't reload on additional calls.  I'm sure that's because of your caching mechanism that I'm not taking into account.  IMO I think this pop-up approach is better than the in file list approach because the file list is already so small.

https://github.com/jneilliii/OctoPrint-GCodeThumbs/tree/jneilliii

**Comment by remcoder** [comment]
I'm sorry but I haven't had the time to look at this in detail. You're right that the popup method solves a number of problems, not only that of the available space but it also helps avoid doing too much computation. 
If you still want to go forward with this I can help you by answering any questions you have. One thing I'm thinking is maybe you can just circumvent the caching if that is blocking. 
I must say that I do like the previews inside the file list still... The primary reason for that is I'd like to be able to visually identify gcode files when scrolling. But if both types of behavior can be turned on/off via settings I don't see why we couldn't have both solutions. 
A third UI option is to put the preview in it's own tab, how do you think about that one?
Anyway, again sorry for not coming back on this earlier.. I really appreciate the time you took so I do plan on finishing and releasing this plugin at some point.

**Comment by jneilliii** [comment]
For me it's a non issue if there's a pop up or not. Recently I've installed the prettygcode plugin and have been very impressed. It actually color codes lines based on verbose gcode output. 

https://github.com/Kragrathea/OctoPrint-PrettyGCode
https://community.octoprint.org/t/wip-prettygcode-viewer/12169

**Comment by remcoder** [comment]
allright, good to know. Thanks for that link, it looks really good.
