### ISSUE TITLE
Preview doesn't work in sub-folders

### ISSUE THREAD

**Issue by leberschnitzel** [remcoder/OctoPrint-GCodeThumbs#5]
Preview works great in the root folder but it doesn't work in subfolders:
https://imgur.com/a/SXguVKp

**Comment by remcoder** [comment]
Thank you for reporting the issue. I did a quick&dirty fix that hopefully resolves the issue.

To try it out you can use the [develop branch](https://github.com/remcoder/OctoPrint-GCodeThumbs/archive/develop.zip). Please let me know if this fixes the issue for you.

~url: https://github.com/remcoder/OctoPrint-GCodeThumbs/archive/develop.zip~ not necessary

**Comment by remcoder** [comment]
This issue was resolved in [v0.2.1](https://github.com/remcoder/OctoPrint-GCodeThumbs/releases/tag/v0.2.1). To update, you will need to manually remove and re-add the plugin.
