### ISSUE TITLE
The plugin is working but no thumbnails can be seen

### ISSUE THREAD

**Issue by ChukasNeves** [remcoder/OctoPrint-GCodeThumbs#7]
![image](https://user-images.githubusercontent.com/29121454/82113891-89eb3c80-9759-11ea-8996-fa7188433893.png)

For some reason the space for the thumbnails has been allocated, but no thumbnails can be seen

**Comment by remcoder** [comment]
I fixed this in v0.2.2. You can install a new version with [this link](https://github.com/remcoder/OctoPrint-GCodeThumbs/archive/v0.2.2.zip).

Please let me know if this works for you.

cheers!

**Comment by ChukasNeves** [comment]
It works now. Thank you for the quick repair!

I only use 3 plugins for octoprint, and GCodeThumbs is one of them. I really like the ability to review what each file was all about.

Thank you for the great work!
with kind regards,

**Comment by remcoder** [comment]
That's nice to hear!

If you have any suggestions for improvement I'm always up to discuss them.
