### ISSUE TITLE
Update to Python 3

### ISSUE THREAD

**Issue by jmlg10** [remcoder/OctoPrint-GCodeThumbs#9]
Hi,

I waswondering if you planned to update your plug-in in order to make it running on Python 3.9.x...

Many Thanks

**Comment by remcoder** [comment]
Hi @jmlg10. To tell you the truth, I had no such plans. I'm not currently using this plugin myself anymore now that PrusaSlicer  has previews [that can be displayed in OctoPrint](https://plugins.octoprint.org/plugins/prusaslicerthumbnails/).

If you're up to it you're welcome to send in a PR. If you do, I'll review and test it and merge it if possible. That being said, even if we update to Python 3, honestly, I don't think this plugin has much future. 

cheers

**Comment by jneilliii** [comment]
because the plugin is so light on python you just need to set the compatibility flag. PR submitted.

**Comment by remcoder** [comment]
Thx for you PR @jneilliii, merged it immediately. 

@jmlg10 please give it a try!
